// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lofordltamdjgaxomebq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZm9yZGx0YW1kamdheG9tZWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzM0MDksImV4cCI6MjA2NDMwOTQwOX0.P4o62oGg7uAhwc8xLLqRdII2tYU7fdtCcU_Fw3KsDY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);